server:
  port: 8089

spring:
  application:
    name: Spring-Redis
    # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cache:
    type: redis
  data:
    redis:
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      timeout: 3000ms # 连接超时时间
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-idle: 8 # 连接池最大空闲连接数
          min-idle: 0 # 连接池最小空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

mybatis-plus:
    #  mapper映射文件包扫描 (这里是对应 resources 的文件路径)
    mapper-locations: classpath:/mapper/*.xml
    #  实体类别名包扫描
    type-aliases-package: com.yingzi.crudMybatisPlus.model.entity