server:
  port: 8090
spring:
  application:
    name: Spring-Redis-Lock
---
spring:
  profiles:
    active: standalone
---
spring:
  config:
    activate:
      on-profile: standalone
  data:
    redis:
      host: localhost
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）